# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dash.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='dash.proto',
  package='dash',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\ndash.proto\x12\x04\x64\x61sh\"l\n\x08\x44\x61shData\x12\r\n\x05speed\x18\x01 \x01(\x02\x12\x0b\n\x03rpm\x18\x02 \x01(\x05\x12\x0c\n\x04gear\x18\x03 \x01(\x05\x12\x0f\n\x07neutral\x18\x04 \x01(\x08\x12\x0e\n\x06\x63lutch\x18\x05 \x01(\x08\x12\x15\n\rengineRunning\x18\x06 \x01(\x08\"\x88\x03\n\x10\x44\x61shExtendedData\x12\x16\n\x0e\x62\x61tteryVoltage\x18\x01 \x01(\x02\x12\x1a\n\x12\x63oolantTemperature\x18\x02 \x01(\x02\x12\x1c\n\x14\x61irIntakeTemperature\x18\x03 \x01(\x02\x12\x18\n\x10manifoldPressure\x18\x04 \x01(\x02\x12\x1e\n\x16throttlePositionSensor\x18\x05 \x01(\x02\x12\x18\n\x10injectorDuration\x18\x06 \x01(\x02\x12\x17\n\x0fignitionAdvance\x18\x07 \x01(\x02\x12\x18\n\x10\x66uelLevelPercent\x18\x08 \x01(\x02\x12\x14\n\x0c\x66uelPressure\x18\t \x01(\x02\x12\x17\n\x0foilLevelPercent\x18\n \x01(\x02\x12\x13\n\x0boilPressure\x18\x0b \x01(\x02\x12\x16\n\x0eoilTemperature\x18\x0c \x01(\x02\x12\x15\n\rlambdaSensor1\x18\r \x01(\x02\x12\x15\n\rlambdaSensor2\x18\x0e \x01(\x02\x12\x11\n\tkickstand\x18\x0f \x01(\x08\" \n\nPlayStatus\x12\x12\n\nplayStatus\x18\x01 \x01(\t\"9\n\tMediaItem\x12\r\n\x05title\x18\x01 \x01(\t\x12\x0e\n\x06\x61rtist\x18\x02 \x01(\t\x12\r\n\x05\x61lbum\x18\x03 \x01(\t\" \n\x0eStatusResponse\x12\x0e\n\x06status\x18\x01 \x01(\x05\x32\x91\x01\n\x0b\x44\x61shControl\x12\x38\n\x0eUpdateDashData\x12\x0e.dash.DashData\x1a\x14.dash.StatusResponse\"\x00\x12H\n\x16UpdateDashExtendedData\x12\x16.dash.DashExtendedData\x1a\x14.dash.StatusResponse\"\x00\x32\x85\x01\n\x0bMediaPlayer\x12=\n\x11PlayStatusChanged\x12\x10.dash.PlayStatus\x1a\x14.dash.StatusResponse\"\x00\x12\x37\n\x0cMediaChanged\x12\x0f.dash.MediaItem\x1a\x14.dash.StatusResponse\"\x00\x62\x06proto3'
)




_DASHDATA = _descriptor.Descriptor(
  name='DashData',
  full_name='dash.DashData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='speed', full_name='dash.DashData.speed', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='rpm', full_name='dash.DashData.rpm', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='gear', full_name='dash.DashData.gear', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='neutral', full_name='dash.DashData.neutral', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='clutch', full_name='dash.DashData.clutch', index=4,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='engineRunning', full_name='dash.DashData.engineRunning', index=5,
      number=6, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=20,
  serialized_end=128,
)


_DASHEXTENDEDDATA = _descriptor.Descriptor(
  name='DashExtendedData',
  full_name='dash.DashExtendedData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='batteryVoltage', full_name='dash.DashExtendedData.batteryVoltage', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='coolantTemperature', full_name='dash.DashExtendedData.coolantTemperature', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='airIntakeTemperature', full_name='dash.DashExtendedData.airIntakeTemperature', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='manifoldPressure', full_name='dash.DashExtendedData.manifoldPressure', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='throttlePositionSensor', full_name='dash.DashExtendedData.throttlePositionSensor', index=4,
      number=5, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='injectorDuration', full_name='dash.DashExtendedData.injectorDuration', index=5,
      number=6, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ignitionAdvance', full_name='dash.DashExtendedData.ignitionAdvance', index=6,
      number=7, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='fuelLevelPercent', full_name='dash.DashExtendedData.fuelLevelPercent', index=7,
      number=8, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='fuelPressure', full_name='dash.DashExtendedData.fuelPressure', index=8,
      number=9, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='oilLevelPercent', full_name='dash.DashExtendedData.oilLevelPercent', index=9,
      number=10, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='oilPressure', full_name='dash.DashExtendedData.oilPressure', index=10,
      number=11, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='oilTemperature', full_name='dash.DashExtendedData.oilTemperature', index=11,
      number=12, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='lambdaSensor1', full_name='dash.DashExtendedData.lambdaSensor1', index=12,
      number=13, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='lambdaSensor2', full_name='dash.DashExtendedData.lambdaSensor2', index=13,
      number=14, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='kickstand', full_name='dash.DashExtendedData.kickstand', index=14,
      number=15, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=131,
  serialized_end=523,
)


_PLAYSTATUS = _descriptor.Descriptor(
  name='PlayStatus',
  full_name='dash.PlayStatus',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='playStatus', full_name='dash.PlayStatus.playStatus', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=525,
  serialized_end=557,
)


_MEDIAITEM = _descriptor.Descriptor(
  name='MediaItem',
  full_name='dash.MediaItem',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='title', full_name='dash.MediaItem.title', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='artist', full_name='dash.MediaItem.artist', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='album', full_name='dash.MediaItem.album', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=559,
  serialized_end=616,
)


_STATUSRESPONSE = _descriptor.Descriptor(
  name='StatusResponse',
  full_name='dash.StatusResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='dash.StatusResponse.status', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=618,
  serialized_end=650,
)

DESCRIPTOR.message_types_by_name['DashData'] = _DASHDATA
DESCRIPTOR.message_types_by_name['DashExtendedData'] = _DASHEXTENDEDDATA
DESCRIPTOR.message_types_by_name['PlayStatus'] = _PLAYSTATUS
DESCRIPTOR.message_types_by_name['MediaItem'] = _MEDIAITEM
DESCRIPTOR.message_types_by_name['StatusResponse'] = _STATUSRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DashData = _reflection.GeneratedProtocolMessageType('DashData', (_message.Message,), {
  'DESCRIPTOR' : _DASHDATA,
  '__module__' : 'dash_pb2'
  # @@protoc_insertion_point(class_scope:dash.DashData)
  })
_sym_db.RegisterMessage(DashData)

DashExtendedData = _reflection.GeneratedProtocolMessageType('DashExtendedData', (_message.Message,), {
  'DESCRIPTOR' : _DASHEXTENDEDDATA,
  '__module__' : 'dash_pb2'
  # @@protoc_insertion_point(class_scope:dash.DashExtendedData)
  })
_sym_db.RegisterMessage(DashExtendedData)

PlayStatus = _reflection.GeneratedProtocolMessageType('PlayStatus', (_message.Message,), {
  'DESCRIPTOR' : _PLAYSTATUS,
  '__module__' : 'dash_pb2'
  # @@protoc_insertion_point(class_scope:dash.PlayStatus)
  })
_sym_db.RegisterMessage(PlayStatus)

MediaItem = _reflection.GeneratedProtocolMessageType('MediaItem', (_message.Message,), {
  'DESCRIPTOR' : _MEDIAITEM,
  '__module__' : 'dash_pb2'
  # @@protoc_insertion_point(class_scope:dash.MediaItem)
  })
_sym_db.RegisterMessage(MediaItem)

StatusResponse = _reflection.GeneratedProtocolMessageType('StatusResponse', (_message.Message,), {
  'DESCRIPTOR' : _STATUSRESPONSE,
  '__module__' : 'dash_pb2'
  # @@protoc_insertion_point(class_scope:dash.StatusResponse)
  })
_sym_db.RegisterMessage(StatusResponse)



_DASHCONTROL = _descriptor.ServiceDescriptor(
  name='DashControl',
  full_name='dash.DashControl',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=653,
  serialized_end=798,
  methods=[
  _descriptor.MethodDescriptor(
    name='UpdateDashData',
    full_name='dash.DashControl.UpdateDashData',
    index=0,
    containing_service=None,
    input_type=_DASHDATA,
    output_type=_STATUSRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='UpdateDashExtendedData',
    full_name='dash.DashControl.UpdateDashExtendedData',
    index=1,
    containing_service=None,
    input_type=_DASHEXTENDEDDATA,
    output_type=_STATUSRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_DASHCONTROL)

DESCRIPTOR.services_by_name['DashControl'] = _DASHCONTROL


_MEDIAPLAYER = _descriptor.ServiceDescriptor(
  name='MediaPlayer',
  full_name='dash.MediaPlayer',
  file=DESCRIPTOR,
  index=1,
  serialized_options=None,
  serialized_start=801,
  serialized_end=934,
  methods=[
  _descriptor.MethodDescriptor(
    name='PlayStatusChanged',
    full_name='dash.MediaPlayer.PlayStatusChanged',
    index=0,
    containing_service=None,
    input_type=_PLAYSTATUS,
    output_type=_STATUSRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='MediaChanged',
    full_name='dash.MediaPlayer.MediaChanged',
    index=1,
    containing_service=None,
    input_type=_MEDIAITEM,
    output_type=_STATUSRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_MEDIAPLAYER)

DESCRIPTOR.services_by_name['MediaPlayer'] = _MEDIAPLAYER

# @@protoc_insertion_point(module_scope)
