# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: media.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='media.proto',
  package='mediaplayer',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0bmedia.proto\x12\x0bmediaplayer\" \n\nPlayStatus\x12\x12\n\nplayStatus\x18\x01 \x01(\t\"9\n\tMediaItem\x12\r\n\x05title\x18\x01 \x01(\t\x12\x0e\n\x06\x61rtist\x18\x02 \x01(\t\x12\r\n\x05\x61lbum\x18\x03 \x01(\t\" \n\x0eStatusResponse\x12\x0e\n\x06status\x18\x01 \x01(\x05\x32\xa1\x01\n\x0bMediaPlayer\x12K\n\x11PlayStatusChanged\x12\x17.mediaplayer.PlayStatus\x1a\x1b.mediaplayer.StatusResponse\"\x00\x12\x45\n\x0cMediaChanged\x12\x16.mediaplayer.MediaItem\x1a\x1b.mediaplayer.StatusResponse\"\x00\x62\x06proto3')
)




_PLAYSTATUS = _descriptor.Descriptor(
  name='PlayStatus',
  full_name='mediaplayer.PlayStatus',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='playStatus', full_name='mediaplayer.PlayStatus.playStatus', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=28,
  serialized_end=60,
)


_MEDIAITEM = _descriptor.Descriptor(
  name='MediaItem',
  full_name='mediaplayer.MediaItem',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='title', full_name='mediaplayer.MediaItem.title', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='artist', full_name='mediaplayer.MediaItem.artist', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='album', full_name='mediaplayer.MediaItem.album', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=62,
  serialized_end=119,
)


_STATUSRESPONSE = _descriptor.Descriptor(
  name='StatusResponse',
  full_name='mediaplayer.StatusResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='mediaplayer.StatusResponse.status', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=121,
  serialized_end=153,
)

DESCRIPTOR.message_types_by_name['PlayStatus'] = _PLAYSTATUS
DESCRIPTOR.message_types_by_name['MediaItem'] = _MEDIAITEM
DESCRIPTOR.message_types_by_name['StatusResponse'] = _STATUSRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PlayStatus = _reflection.GeneratedProtocolMessageType('PlayStatus', (_message.Message,), {
  'DESCRIPTOR' : _PLAYSTATUS,
  '__module__' : 'media_pb2'
  # @@protoc_insertion_point(class_scope:mediaplayer.PlayStatus)
  })
_sym_db.RegisterMessage(PlayStatus)

MediaItem = _reflection.GeneratedProtocolMessageType('MediaItem', (_message.Message,), {
  'DESCRIPTOR' : _MEDIAITEM,
  '__module__' : 'media_pb2'
  # @@protoc_insertion_point(class_scope:mediaplayer.MediaItem)
  })
_sym_db.RegisterMessage(MediaItem)

StatusResponse = _reflection.GeneratedProtocolMessageType('StatusResponse', (_message.Message,), {
  'DESCRIPTOR' : _STATUSRESPONSE,
  '__module__' : 'media_pb2'
  # @@protoc_insertion_point(class_scope:mediaplayer.StatusResponse)
  })
_sym_db.RegisterMessage(StatusResponse)



_MEDIAPLAYER = _descriptor.ServiceDescriptor(
  name='MediaPlayer',
  full_name='mediaplayer.MediaPlayer',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=156,
  serialized_end=317,
  methods=[
  _descriptor.MethodDescriptor(
    name='PlayStatusChanged',
    full_name='mediaplayer.MediaPlayer.PlayStatusChanged',
    index=0,
    containing_service=None,
    input_type=_PLAYSTATUS,
    output_type=_STATUSRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='MediaChanged',
    full_name='mediaplayer.MediaPlayer.MediaChanged',
    index=1,
    containing_service=None,
    input_type=_MEDIAITEM,
    output_type=_STATUSRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_MEDIAPLAYER)

DESCRIPTOR.services_by_name['MediaPlayer'] = _MEDIAPLAYER

# @@protoc_insertion_point(module_scope)
